//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.23 at 12:43:38 PM GST 
//


package com.shafafiya.webapi.webservice.live;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GetInsuranceContinuityCertificateResult" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="FoundTransactions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="errorMessage" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "getInsuranceContinuityCertificateResult",
    "foundTransactions",
    "errorMessage"
})
@XmlRootElement(name = "GetInsuranceContinuityCertificateResponse")
public class GetInsuranceContinuityCertificateResponse {

    @XmlElement(name = "GetInsuranceContinuityCertificateResult")
    protected int getInsuranceContinuityCertificateResult;
    @XmlElement(name = "FoundTransactions")
    protected String foundTransactions;
    protected String errorMessage;

    /**
     * Gets the value of the getInsuranceContinuityCertificateResult property.
     * 
     */
    public int getGetInsuranceContinuityCertificateResult() {
        return getInsuranceContinuityCertificateResult;
    }

    /**
     * Sets the value of the getInsuranceContinuityCertificateResult property.
     * 
     */
    public void setGetInsuranceContinuityCertificateResult(int value) {
        this.getInsuranceContinuityCertificateResult = value;
    }

    /**
     * Gets the value of the foundTransactions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFoundTransactions() {
        return foundTransactions;
    }

    /**
     * Sets the value of the foundTransactions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFoundTransactions(String value) {
        this.foundTransactions = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

}
