//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.23 at 12:43:38 PM GST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "https://www.shafafiya.org/v2/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.shafafiya.webapi.webservice.live;
